# Generated by Django 5.0.7 on 2024-08-03 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='raiting',
            new_name='rating',
        ),
    ]
