# Generated by Django 5.0.7 on 2024-08-06 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_reviews_product_alter_reviews_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='img_product',
        ),
        migrations.CreateModel(
            name='ImagesByProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_1', models.ImageField(blank=True, upload_to='products/<django.db.models.fields.related.ForeignKey>')),
                ('img_2', models.ImageField(blank=True, upload_to='products/<django.db.models.fields.related.ForeignKey>')),
                ('img_3', models.ImageField(blank=True, upload_to='products/<django.db.models.fields.related.ForeignKey>')),
                ('img_4', models.ImageField(blank=True, upload_to='products/<django.db.models.fields.related.ForeignKey>')),
                ('img_5', models.ImageField(blank=True, upload_to='products/<django.db.models.fields.related.ForeignKey>')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
