# Generated by Django 5.0.7 on 2024-08-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_products_img_product_imagesbyproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesbyproducts',
            name='img_1',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='imagesbyproducts',
            name='img_2',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='imagesbyproducts',
            name='img_3',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='imagesbyproducts',
            name='img_4',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='imagesbyproducts',
            name='img_5',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
    ]
