# Generated by Django 5.0.7 on 2024-10-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_imagesbyproducts_img_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='nombre_user',
            field=models.CharField(max_length=255),
        ),
    ]
