# Generated by Django 5.0.7 on 2024-08-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userName', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('birth', models.DateField()),
                ('dateJoined', models.DateTimeField(auto_now_add=True)),
                ('dateLogin', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('isStaff', models.BooleanField(default=False)),
                ('isSuperuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
