# Generated by Django 5.0.7 on 2024-08-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='userName',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birth',
            field=models.DateField(null=True),
        ),
    ]
