# Generated by Django 5.0.7 on 2024-08-17 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_username_customuser_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='isStaff',
            new_name='is_staff',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='isSuperuser',
            new_name='is_superuser',
        ),
    ]
